services:
  mongo_prod:
    profiles:
      - prod
    image: mongo:latest
    expose:
      - 27017
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${DB}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}

  mongo:
    profiles:
      - dev
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${DB}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}

  server:
    profiles:
      - prod
    build: .
    ports:
      - "${PORT}:${PORT}"
    restart: always
    environment:
      PORT: ${PORT}
      HOST: ${HOST}
      NEXT_HOST: ${NEXT_HOST}
      MONGODB_URI: mongodb://${DB_USER}:${DB_PASSWORD}@mongo_prod:27017?retryWrites=true&w=majority
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      EMAIL_FROM: ${EMAIL_FROM}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
