services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${DB}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}

  server:
    build: .
    ports:
      - "${PORT}:${PORT}"
    restart: always
    environment:
      PORT: ${PORT}
